### PR TITLE
Update ensemble comparison score data

### PR DESCRIPTION
**Pull request by kathsherratt**
Updates comparisons among ensembles (weighted v unweighted, mean v median), following a bug fixed by @sbfnk and enforcing a minimum 3 models to create each ensemble.

For the data update, see
- The `assess-ensembles-update` branch: https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/tree/assess-ensembles-update
- The workflow used is outlined here: https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/assess-ensembles-update/ensembles/assess-ensembles.R

This PR pulls the newly updated scores which then just slot in to the existing paper.

Comparison against previous results: scores seem to have increased (worsened) overall, but with little effect on the relative conclusions discussed in the paper text (median beats mean in all except 1 week cases, weighting helps somewhat for mean, not for median). 

Paper text around these results with suggested changes [ ~~old~~ _new_ ]:

> We considered alternative methods for creating ensembles from the participating forecasts, using either a
> mean or median to combine either weighted or unweighted forecasts (Table 1). Across locations we observed
> that the median outperformed the mean across all one through four week horizons and both cases and death
> targets, for all but cases at the 1 week horizon. This held regardless of whether the component forecasts were
> weighted or unweighted by their individual past performance. Between methods of combination, weighting
> ~~made little difference to~~ _typically worsened_ the performance of the median ensemble, but ~~slightly~~ improved performance of the mean ensemble.

New scores:
image

Original scores:
image

### CODE REVIEW

**Comment by sbfnk** [comment]
This all looks good to me but you'll have to run it once more as I found [another bug](https://github.com/covid19-forecast-hub-europe/EuroForecastHub/pull/23) when enforcing >=3 models (sorry!).

**Comment by kathsherratt** [comment]
Thanks so much (again)! All done. As before, new scores are not much different to the original scores, except for the unweighted mean of deaths with worse scores at all horizons.

Results text can remain the same as the stronger wording suggestion above. 

Updated table:
image



to check I also looked at it another way to directly see weighted v unweighted scores. (reference line = parity between weighted and unweighted)
image

**Comment by sbfnk** [comment]
Nice. Has something gone wrong with the order for Deaths (4 weeks then 1 week), or are they wrongly labelled? The unweighted mean performance is really confusing.

This is using the latest data and anomalies file, right? Not the data and anomalies as of 7 March 2022 (the last date considered, right?), which would also contribute to the difference in score. Do you think we might want to use the data and anomalies as of 7 March, or some other date? This would be doing something like [here](https://github.com/epiforecasts/log-or-not/blob/68dc9f2454d666846d4efb78e80480b5395c32dc/R/Analysis%20ECDC%20forecasts.Rmd#L76).

**Comment by kathsherratt** [comment]
I agree the result with the unweighted mean doesn't make sense and doesn't fit with any other results we've seen from previous evaluations either. I am absolutely sure this weird result has been introduced by a bug, especially given an earlier comment from Seb:

> One thing I looked at earlier this week (and was how I found the other bug) was to compare the scores with min_nmodels=0 and min_nmodels=3 in the assess-ensembles-update branch. Once my bug was fixed there was not difference between the two because we always had at least 3 models for all case/death forecasts up to March 2022. This means any other major changes to the table must come from something else, hence my question about anomalies (which I think did get expanded quite a bit sometime this year when we switched to detecting them automatically).

I suspect it's something to do with three extreme values for the `rel_wis` of unweighted mean ensemble in Ireland. It looks to me like these should have been excluded and aren't
image

Rationally and as in Seb's comment this PR should in any case be redundant - there should be zero change in the scores after re-running following a bug fix as the fix only applied to ensembles after the evaluation period looked at here. The latest run of results that was sent round co-authors (ie the one Seb was comparing to and found no difference from) was already using the latest anomalies file, so I don't think it is that. 

So in this branch I only seem to have introduced a bug. I can't find the bug despite very many attempts at checking from different dates, reverting different parts of the code, which is confusing. Therefore I am closing this PR for now to get the rest of the paper turned around.

**Comment by sbfnk** [comment]
Having had another look at these scores from Ireland it seems that [this](https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/main/data-processed/ILM-EKF/2022-02-14-ILM-EKF.csv#L278) (cases) and [this](https://github.com/covid19-forecast-hub-europe/covid19-forecast-hub-europe/blob/main/data-processed/ILM-EKF/2022-02-14-ILM-EKF.csv#L854) (deaths) forecast by the `ILM-EKF` model are the culprits for blowing up these (hugely influential) scores - making a good case for median ensembles!

However, I think the differences you found come from another issue, which is related to the fact that the relative WIS values depend on which models are included in the pairwise comparison. It seems to me that the [file used in the original version](https://github.com/covid19-forecast-hub-europe/euro-hub-ensemble/blob/8c3993d49e75a365894892a1229b9854610979b6/data/scores-ensemble.csv) came from the `assess-ensembles` branch where quite a few more model options were assessed than shown in the table (including with a 10 week cutoffs for which scores to consider for the weighted ensembles, and with versions only considering models performing better than the models). Adding more models with similar performance generally seems to bring the geometric means closer to 1, and thus all scores closer to each other, ending up with scaled relative WIS values closer to 1. In the `assess-ensembles-update` branch you excluded those models before calculating the relative WIS values, which I think makes more sense when comparing these models - so I think of the two your updated version is actually the one to prefer.

More generally though I find that the property that the relative WIS values change depending on which models are included in the comparison makes it a bit hard to interpret - we haven't really found another good option when comparing the individual models as they drop in and out and cover different number of countries, however for the ensembles we don't have this problem as they all cover all times and all countries. Would it perhaps make sense to just use the ratio of WIS values of the ensembles to the baseline in this table? This would be using the `mean_score_ratio` column when `compare_against == "EuroCOVIDhub-baseline"` instead of `scaled_rel_skill` in the [summarise_scores](https://github.com/covid19-forecast-hub-europe/EuroForecastHub/blob/14b43e2dc615c0c218748c65cc209ac83c6faa0e/R/summarise_scores.R#L96) function (which we could make an option to this function).

**Comment by kathsherratt** [comment]
Thanks so much for checking this Seb and I'm sorry for the problems.  I think what you suggest does make sense, and comparing to the ensemble rather than the baseline definitely seems right to me. I'll implement ASAP.

**Comment by sbfnk** [comment]
> comparing to the ensemble rather than the baseline definitely seems right to me

Just to avoid misunderstanding: my suggestion was to still compare to the baseline (just using WIS / WIS(baseline) directly rather than doing pairwise tournament first) - although if you're suggesting to e.g. compare to e.g. the mean ensemble then I think that also makes a lot of (and perhaps more) sense.

**Comment by kathsherratt** [comment]
Completed in `main`

**Pull request closed without merging**
